// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCer3bIYmkwi-sCgCX1gx90n446RgIxAMY',
    appId: '1:201901974175:web:70616360182cbd5bd738aa',
    messagingSenderId: '201901974175',
    projectId: 'finpal-ebfd3',
    authDomain: 'finpal-ebfd3.firebaseapp.com',
    storageBucket: 'finpal-ebfd3.appspot.com',
    measurementId: 'G-W9062D7SF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3GFDHXVVdJ86IvQv_bn2lVyA4C8ArHg',
    appId: '1:201901974175:android:37d62f4705898043d738aa',
    messagingSenderId: '201901974175',
    projectId: 'finpal-ebfd3',
    storageBucket: 'finpal-ebfd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArDkd5mIp7vM2hwcGXvd7RnRejspDikjI',
    appId: '1:201901974175:ios:95a15ab74138e463d738aa',
    messagingSenderId: '201901974175',
    projectId: 'finpal-ebfd3',
    storageBucket: 'finpal-ebfd3.appspot.com',
    iosBundleId: 'com.example.finpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArDkd5mIp7vM2hwcGXvd7RnRejspDikjI',
    appId: '1:201901974175:ios:95a15ab74138e463d738aa',
    messagingSenderId: '201901974175',
    projectId: 'finpal-ebfd3',
    storageBucket: 'finpal-ebfd3.appspot.com',
    iosBundleId: 'com.example.finpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCer3bIYmkwi-sCgCX1gx90n446RgIxAMY',
    appId: '1:201901974175:web:7d4005a4f868e49cd738aa',
    messagingSenderId: '201901974175',
    projectId: 'finpal-ebfd3',
    authDomain: 'finpal-ebfd3.firebaseapp.com',
    storageBucket: 'finpal-ebfd3.appspot.com',
    measurementId: 'G-TM6VYLNY03',
  );
}
